# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- "*"
stages:
  - stage: test
    jobs:
      - job: validationtest
        pool:
          vmImage: window-latest
        steps:
        - task: AzureResourceManagerTemplateDeployment@3
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: 'Pipeline_ARM_Template'
            subscriptionId: 'd322face-c3fa-408d-8c81-732800d9372a'
            action: 'Create Or Update Resource Group'
            resourceGroupName: 'MerazRG'
            location: 'East US'
            templateLocation: 'Linked artifact'
            csmFile: '$(Build.SourcesDirectory)/CI_CD_Artifacts/blob/main/template.json'
            csmParametersFile: '$(Build.SourcesDirectory)/CI_CD_Artifacts/blob/main/parameters.json'
            deploymentMode: 'Validation'
        - task: PowerShell@2
          displayName: 'check for the deletion'
          inputs:
            targetType: 'inline'
            script: |
              Install-Module Az.Resources -RequiredVersion 1.12.1-preview -AllowPrerelease -Force -Scope CurrentUser
              $Parameters = @{
                ResourcegroupName     = "ARMDeploymentTest"
                Templatefile          = ".\CI_CD_Artifacts/blob/main/template.json"
                TemplateParameterfile = ".\CI_CD_Artifacts/blob/main/parameters.json"
                Mode                  = 'Incremental'
               }
              $Result = Get-AzResourceGroupDeploymentWhatIfResult @Parameters
              $Result
            failOnStderr: true
          

            
